### ISSUE TITLE
立春算法里并没有匹配到时辰

### ISSUE THREAD

**Issue by qx** [OPN48/cnlunar#22]
举个例子1993 0203 20:00 是壬申。0204 00:00依然应该是壬申 , 到4点左右才应该立春,走到癸酉,而不是简单的以天为界限

**Comment by cuba3** [comment]
> 举个例子1993 0203 20:00 是壬申。0204 00:00依然应该是壬申 , 到4点左右才应该立春,走到癸酉,而不是简单的以天为界限

老问题。老回答：1、您如果有更精确的数据，可以自行替换数据源，目前采用香港天文台数据；2、《钦定协纪辨方书》并未说明以时辰区隔二十四节气。

**Comment by cuba3** [comment]
> 举个例子1993 0203 20:00 是壬申。0204 00:00依然应该是壬申 , 到4点左右才应该立春,走到癸酉,而不是简单的以天为界限

详见香港天文台原网页https://www.hko.gov.hk/sc/gts/time/conversion.htm

**Comment by qx** [comment]
> 

关于要不要精确到时分,这个很难判定,不过很多别的地方我看了下他们是精确到时分的,因为八字来说差之毫厘失之千里,有没有是一回事,精确与否又是另一回事,而且作为八字来说,农历新年应该是立春开始算,还不是正月初一,这是袁大头那会改了,以前是一样的.

**Comment by cuba3** [comment]
> > 
> 
> 关于要不要精确到时分,这个很难判定,不过很多别的地方我看了下他们是精确到时分的,因为八字来说差之毫厘失之千里,有没有是一回事,精确与否又是另一回事,而且作为八字来说,农历新年应该是立春开始算,还不是正月初一,这是袁大头那会改了,以前是一样的.

1、很多项目代码精确到分秒的，并不是观测或者查表，而是直接用寿星通式算的，目前开放数据只有今明两年大致能精确到小时分，如果寿星通式则在很多年份会差到一两天，所以还是依赖数据源。
2、袁世凯改什么内容，无历书通书考究，本项目在论文撰写之初就发现不同版本历书、通书之间差异巨大，算法差异巨大，《钦定协纪辨方书》算是对所有收集的历书通书进行辩证合并，但依然存在许多矛盾，在八字、农历月柱、农历月份对值神计算也有所冲突，所以本项目提供了两种算法；
3、立春的那个在最新版本已经添加了参数，您可以根据需要自行切换`# a = cnlunar.Lunar(datetime.datetime(2022, 2, 3, 10, 30), godType='8char', year8Char='beginningOfSpring')  # 八字立春切换算法`
4、农历本质上还是农业文明的天文历书产物，实际上不存在失之毫厘谬以千里的说法，本项目不认可任何封建迷信内容，您如果对算法上不认可，可以fork之后自行改参，本论文发布于厦门大学，数据来源算法依然需要尊重引用原则，任何非著作类、史料类、科学观测类数据不作引用。

**Comment by qx** [comment]
不讨论了,项目还是个好项目,需求不同
