### ISSUE TITLE
v0.09 install problem fixed

### ISSUE THREAD

**Issue by mickey3721** [OPN48/cnlunar#23]
problem during installation:

File "<string>", line 9, in <module>
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xb4 in position 89: illegal multibyte sequence

fix setup.py by adding code: encoding='utf-8' in 'long_description=' as below:

from setuptools import setup
setup(
    name='cnlunar',
    version='0.0.9',
    packages=['cnlunar'],
    url='https://github.com/OPN48/cnLunar',
    author='cuba3',
    author_email='cuba3@163.com',
    _**long_description=open('README.rst',encoding='utf-8').read(),**_
)

**Comment by cuba3** [comment]
> 

add encoding='utf-8' in v0.1.0 , Thx for ur add
