### ISSUE TITLE
神煞-天愿，疑问

### ISSUE THREAD

**Issue by JeremyYoungCai** [OPN48/cnlunar#24]
('天愿', '甲子癸未甲午甲戌乙酉丙子丁丑戊午甲寅丙辰辛卯戊辰'[men], d,

1.是不是格式存在错误
2.我在百度搜索 天愿日
http://ygkyfs.com/wap.php?action=article&id=28077
发现数据也存在差异，不知道那个是正确的

**Comment by cuba3** [comment]
确实是写法错误，已修复

**Comment by cuba3** [comment]
> 确实是写法错误，已修复

pip 已更新到0.1.1

**Comment by cuba3** [comment]
> ('天愿', '甲子癸未甲午甲戌乙酉丙子丁丑戊午甲寅丙辰辛卯戊辰'[men], d,
> 
> 1.是不是格式存在错误 2.我在百度搜索 天愿日 http://ygkyfs.com/wap.php?action=article&id=28077 发现数据也存在差异，不知道那个是正确的

pip3 install cnlunar==0.1.1
