### ISSUE TITLE
大佬，上一个节气怎么获取？

### ISSUE THREAD

**Issue by hyfclimber** [OPN48/cnlunar#27]
看到下一个节气有nextSolarTermDate，和nextSolarTermYear，不知道上一个节气怎么获取呢？八字推大运的时候有反向拿的case。
有没有计划增加个last方法呢？ღ( ´･ᴗ･` )比心

**Comment by cuba3** [comment]
问：上一个是怎么定义的

> 看到下一个节气有nextSolarTermDate，和nextSolarTermYear，不知道上一个节气怎么获取呢？八字推大运的时候有反向拿的case。 有没有计划增加个last方法呢？ღ( ´･ᴗ･` )比心

问：上一个是怎么定义的，

**Comment by hyfclimber** [comment]
谢谢
