### ISSUE TITLE
lunar.py: 第1053行 if 条件始终为'true'

### ISSUE THREAD

**Issue by JeremyYoungCai** [OPN48/cnlunar#37]
文件  : [https://github.com/OPN48/cnlunar/lunar.py](url) ;

### 第一个：
```
# 凡德合、赦愿、月恩、四相、时德等日，不注忌进人口、安床、经络、酝酿、开市、立券、交易、纳财、开仓库、出货财。如遇德犹忌，及从忌不从宜之日，则仍注忌。
temp = False
for i in self.goodGodName:
    if i in ['岁德合', '月德合', '天德合', '天赦', '天愿', '月恩', '四相', '时德']:
        temp = True
        break
if temp:
    # 如遇德犹忌，及从忌不从宜之日，则仍注忌。
    if i not in deIsBadThing or thingLevel != 2:
        self.badThing = rfRemove(self.badThing, ['进人口', '安床', '经络', '酝酿', '开市', '立券交易', '纳财', '开仓库', '出货财'])

```
其中 
> if i not in deIsBadThing or thingLevel != 2: 

  ` i`  是 ['岁德合', '月德合', '天德合', '天赦', '天愿', '月恩', '四相', '时德'] 集合中的一个与`deIsBadThing`集合 不是一种类型; 判断条件永远都为 true; 所以这儿可以删除？还是将`deIsBadThingDic` 误写成`deIsBadThing`?

###  第二个：
```
    # 凡四忌、四穷只忌安葬。如遇鸣吠、鸣吠对亦不注宜破土、启攒。
    if '四忌' in self.badGodName or '四忌' in self.badGodName:
```
>  if '四忌' in self.badGodName or '四忌' in self.badGodName:
 这行填写错误 其中一个`四忌` 应写成  `四穷` ,即：
>  if '四忌' in self.badGodName or '四穷' in self.badGodName:

**Comment by cuba3** [comment]
> 文件 : [https://github.com/OPN48/cnlunar/lunar.py](url) ;
> 
> ### 第一个：
> ```
> # 凡德合、赦愿、月恩、四相、时德等日，不注忌进人口、安床、经络、酝酿、开市、立券、交易、纳财、开仓库、出货财。如遇德犹忌，及从忌不从宜之日，则仍注忌。
> temp = False
> for i in self.goodGodName:
>     if i in ['岁德合', '月德合', '天德合', '天赦', '天愿', '月恩', '四相', '时德']:
>         temp = True
>         break
> if temp:
>     # 如遇德犹忌，及从忌不从宜之日，则仍注忌。
>     if i not in deIsBadThing or thingLevel != 2:
>         self.badThing = rfRemove(self.badThing, ['进人口', '安床', '经络', '酝酿', '开市', '立券交易', '纳财', '开仓库', '出货财'])
> ```
> 
> 其中
> 
> > if i not in deIsBadThing or thingLevel != 2:
> 
> ` i` 是 ['岁德合', '月德合', '天德合', '天赦', '天愿', '月恩', '四相', '时德'] 集合中的一个与`deIsBadThing`集合 不是一种类型; 判断条件永远都为 true; 所以这儿可以删除？还是将`deIsBadThingDic` 误写成`deIsBadThing`?
> 
> ### 第二个：
> ```
>     # 凡四忌、四穷只忌安葬。如遇鸣吠、鸣吠对亦不注宜破土、启攒。
>     if '四忌' in self.badGodName or '四忌' in self.badGodName:
> ```
> 
> > if '四忌' in self.badGodName or '四忌' in self.badGodName:
> > 这行填写错误 其中一个`四忌` 应写成  `四穷` ,即：
> > if '四忌' in self.badGodName or '四穷' in self.badGodName:

1、deIsBadThing内容是【遇德犹忌】的事，这时候i是【值神】，确实不是一个类，我翻一下原文修改一下
2、四忌、四穷 bug已修复

已将您加入到readme 特别鸣谢中，感谢您如此细致地发现错误，很荣幸能在开源项目里和您并肩作战
