### ISSUE TITLE
get_AngelDemon 方法下的 demon 数据里，地囊 一处录入了空的 string 数据

### ISSUE THREAD

**Issue by Sonic853** [OPN48/cnlunar#42]
https://github.com/OPN48/cnlunar/blob/376fe5bb049d2c9d61a252cb59edcdae300b4089/cnlunar/lunar.py#L889-L892

`'庚戌庚子', ][men]` 这一处的数据是否为有意而为？

**Comment by cuba3** [comment]
python语法中……['1',] == ['1']  （true），属于书写时候复制粘贴的习惯，不会有空的string

**Comment by cuba3** [comment]
刚好修了一个bug，与这个有关，发布到0.1.9了

0.1.8bug
>>> list(('冠带'))
['冠', '带']

修复后
>>> list(('冠带',))
['冠带']

**Comment by Sonic853** [comment]
理解了，是python的特性
